config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search', :as => 'search_page'
  resources :tweets, only: %i[index show]
  resources :targets, only: %i[index show]
  resources :insults, only: %i[index show]

  root to: "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insult.rb
class Insult < ApplicationRecord
  has_many :tweet_insults
  has_many :tweets, through: :tweet_insults
  validates :text, presence: true
end

app/models/target.rb
class Target < ApplicationRecord
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :tweet_insults
  has_many :insults, through: :tweet_insults
  belongs_to :target
  validates :date, :message, presence: true

  def insults_list
    self.insults.map(&:text).join(", ")
  end
end

app/models/tweet_insult.rb
class TweetInsult < ApplicationRecord
  belongs_to :tweet
  belongs_to :insult
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/insults_controller.rb
class InsultsController < ApplicationController
  def index
    @insults = Insult.includes(:tweets).page(params[:page]).per(21)
  end

  def show
    @insult = Insult.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:search].blank?
      redirect_to(root_path) and return
    else
      @parameter = params[:search].downcase
      @results = Insult.all.where("lower(text) LIKE :search", search: "%#{@parameter}%")
    end
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  def index
    @targets = Target.page(params[:page]).per(21)
  end

  def show
    @target = Target.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.order(date: :desc).page(params[:page]).per(5)
  end

  def show
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insults_helper.rb
module InsultsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/insults/index.html.erb
<%= paginate @insults %>

<div class="row">
<% @insults.each do |insult| %>
  <div class="col-sm-4">
    <div class="card mb-4">
      <div class="card-body">
        <figure class="text-center">
          <blockquote class="blockquote">
            <p>" <%= link_to insult.text, insult %> "</p>
          </blockquote>
          <figcaption class="blockquote-footer">
            Donald J. Trump <cite title="Source Title">Former President, USA</cite>
          </figcaption>
        </figure>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/insults/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">🤬  " <%= @insult.text %> "</h5>
    <hr>
<% @insult.tweets.each do |insult| %>
      <div class="card my-3">
        <div class="card-body">
         <h4>🐥 " <span class="text-danger"><%= link_to insult.message, insult %></span> "</h4>
          <small class="text-muted"><%= insult.date.strftime("%b %d, %Y") %></small>
        </div>
      </div>
    <% end %>
    <hr>
    <a href="<%= insults_path %>" class="btn btn-danger">View All 🤬</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
      <div class="container">
        <a class="navbar-brand fw-bolder text-uppercase" href="/">Make Trump Great Again</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto me-5">
            <li class="nav-item mx-3">
              <a class="nav-link btn btn-warning btn-sm px-3" href="/">🐥</a>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link btn btn-success btn-sm px-3" href="/targets">🚀</a>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link btn btn-danger btn-sm px-3" href="/insults">🤬</a>
            </li>
          </ul>
          <%= form_tag(search_page_path, :method => "get",
              class: 'd-flex') do %>
            <div class="input-group">
              <%= search_field_tag :search, params[:search], placeholder: "Search for an insult", class: "form-control" %>
              <div class="input-group-btn">
                <%= button_tag "Submit", :class => 'btn btn-primary', :name => nil %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>

app/views/search/search.html.erb
<h3 class="mb-3">Search Result</h3>

  <% @results.each do |result| %>
      <%= link_to result.text, result %><br>
  <% end %>

app/views/targets/index.html.erb
<%= paginate @targets %>

<div class="row">
<% @targets.each do |target| %>
  <div class="col-sm-4">
    <div class="card mb-4">
      <div class="card-body">
        🚀 <%= link_to target.prey.gsub('-', ' ').titleize, target %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/targets/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">🚀 <%= @target.prey.gsub('-', ' ').titleize %></h5>
    <hr>
    <% @target.tweets.each do |target| %>
      <div class="card my-3">
        <div class="card-body">
         <h4>🤬 " <span class="text-danger"><%= link_to target.insults.first.text, target.insults.first %></span> "</h4><br />
          🐥 <%= link_to target.message, target %><br />
          <small class="text-muted"><%= target.date.strftime("%b %d, %Y") %></small>
        </div>
      </div>
    <% end %>
    <hr>
    <a href="<%= targets_path %>" class="btn btn-warning">View All 🚀 </a>
  </div>
</div>

app/views/tweets/index.html.erb
<%= paginate @tweets %>

<% @tweets.each do |tweet| %>
<div class="card my-5">
  <h5 class="card-header fw-bolder bg-white py-3 ps-4">
    Tweet
  </h5>
  <div class="card-body">
    <div class="row">
      <div class="col-md-auto">
        <img src="https://cdn.geekwire.com/wp-content/uploads/2017/06/trumptwitter.jpg" width="50px" height="50px" class="rounded-circle">
      </div>
      <div class="col px-0">
        <p class="card-title fw-bold mb-0">Donald J. Trump</p>
        <p class="card-title text-secondary"><small>@realDonaldTrump</small></p>
      </div>
    </div>

    <p class="card-text fs-5"><%= tweet.message %></p>
    <div class="row">
      <small class="card-title text-secondary ml-4">
        <%= link_to "View attack details", tweet %> &bull;
        <%= tweet.date.strftime("%b %d, %Y") %>
      </small>
    </div>
  </div>
</div>
<% end %>

app/views/tweets/show.html.erb
<div class="m-2 mb-5">
  <figure>
    <blockquote class="blockquote">
      <p><%= @tweet.message %></p>
    </blockquote>
    <figcaption class="blockquote-footer">
      Donald J. Trump, <cite title="Source Title">President of the United States</cite>
    </figcaption>
  </figure>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">🚀 Target: <%= link_to @tweet.target.prey.gsub('-', ' ').titleize,  @tweet.target %></h5>
    <hr>
    <h5 class="card-title">🤬 Insult: " <span class="text-danger"><%= link_to @tweet.insults.first.text, @tweet.insults.first %></span> "</h5>
    <hr>
    <a href="<%= tweets_path %>" class="btn btn-warning">View All Tweets</a>
  </div>
</div>